[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Extensions.intl", "php82Extensions.zip", "php82Extensions.mbstring", "php82Extensions.pdo", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction"]

[phases.build]
cmds = [
    "npm ci --legacy-peer-deps",
    "npm run build"
]

[start]
cmd = "bash ./railway-deploy.sh && php artisan serve --host=0.0.0.0 --port=$PORT"
