[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["php8.2", "php8.2-intl", "php8.2-zip", "php8.2-mbstring", "php8.2-xml", "php8.2-curl", "php8.2-mysql"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction"]

[phases.build]
cmds = [
    "npm ci --legacy-peer-deps",
    "npm run build"
]

[start]
cmd = "bash ./railway-deploy.sh && php artisan serve --host=0.0.0.0 --port=$PORT"
